"""Tests for WS handler improvements — audio MIME detection and lazy STT."""
from __future__ import annotations

import asyncio
import base64
import io
import math
import json
import wave
import time

import pytest

from app.avatar.emotion_mapper import EmotionMapper
from app.avatar.state_machine import ConversationStateMachine
from app.config import config
from app.llm.streaming import SentenceChunker
from app.voice.stt_service import FasterWhisperSTTService
from app.voice.tts_service import FillerAudioService
from app.ws.handler import AvatarWebSocketHandler, POST_TTS_HOLDOFF_MS, _detect_audio_mime


class TestDetectAudioMime:
    def test_mp3_id3_tag(self):
        assert _detect_audio_mime(b"ID3\x04\x00\x00" + b"\x00" * 10) == "audio/mpeg"

    def test_mp3_sync_word(self):
        assert _detect_audio_mime(b"\xff\xfb\x00\x00") == "audio/mpeg"

    def test_wav_riff(self):
        assert _detect_audio_mime(b"RIFF\x00\x00\x00\x00WAVE") == "audio/wav"

    def test_ogg(self):
        assert _detect_audio_mime(b"OggS\x00\x00") == "audio/ogg"

    def test_webm(self):
        assert _detect_audio_mime(b"\x1aE\xdf\xa3" + b"\x00" * 4) == "audio/webm"

    def test_empty_bytes(self):
        assert _detect_audio_mime(b"") == "audio/wav"

    def test_unknown_magic(self):
        assert _detect_audio_mime(b"\xde\xad\xbe\xef") == "application/octet-stream"

    def test_real_sine_wav(self):
        """WAV bytes generated by FallbackTTS should be detected correctly."""
        n = 4410
        buf = io.BytesIO()
        with wave.open(buf, "wb") as w:
            w.setnchannels(1); w.setsampwidth(2); w.setframerate(22050)
            frames = bytearray()
            for i in range(n):
                amp = int(8000 * math.sin(2 * math.pi * 220 * i / 22050))
                frames.extend(int(amp).to_bytes(2, "little", signed=True))
            w.writeframes(bytes(frames))
        audio = buf.getvalue()
        assert _detect_audio_mime(audio) == "audio/wav"


class TestLazySTTLoading:
    def test_not_loaded_on_init(self):
        """Model must NOT be loaded during __init__ when warmup is disabled."""
        prev = config.stt_warmup_enabled
        config.stt_warmup_enabled = False
        try:
            svc = FasterWhisperSTTService()
            assert svc._model is None
            assert svc._load_attempted is False
        finally:
            config.stt_warmup_enabled = prev

    def test_empty_audio_skips_load(self):
        """Empty audio bytes should return early without triggering model load."""
        prev = config.stt_warmup_enabled
        config.stt_warmup_enabled = False
        try:
            svc = FasterWhisperSTTService()
            result = svc.transcribe(b"")
            assert result == ""
            assert svc._load_attempted is False  # load should NOT be triggered for empty audio
        finally:
            config.stt_warmup_enabled = prev

    def test_transcribe_triggers_load(self):
        """Non-empty audio triggers model load attempt."""
        svc = FasterWhisperSTTService()
        # Provide minimal fake WAV so it doesn't crash before load
        n = 100
        buf = io.BytesIO()
        with wave.open(buf, "wb") as w:
            w.setnchannels(1); w.setsampwidth(2); w.setframerate(16000)
            w.writeframes(b"\x00" * n * 2)
        wav_bytes = buf.getvalue()

        # This may succeed or fail depending on whether whisper model is available
        # but _load_attempted MUST be True after calling transcribe with non-empty audio
        try:
            svc.transcribe(wav_bytes)
        except Exception:
            pass
        assert svc._load_attempted is True


class _FakeWS:
    def __init__(self, messages: list[dict]):
        self._messages = [json.dumps(m) for m in messages]
        self.sent: list[dict] = []

    async def accept(self):
        return None

    async def receive_text(self):
        if self._messages:
            return self._messages.pop(0)
        from fastapi import WebSocketDisconnect
        raise WebSocketDisconnect()

    async def send_json(self, data):
        self.sent.append(data)


class _StubTTS:
    def synthesize(self, text: str):
        return b"RIFF" + b"\x00" * 64, []


class _StubSTT:
    def __init__(self, text: str = "hello"):
        self.text = text
        self.calls = 0

    def transcribe(self, audio_bytes: bytes):
        self.calls += 1
        return self.text


class _StubVAD:
    def __init__(self, segments):
        self._segments = segments

    def detect(self, audio_bytes: bytes, sample_rate: int = 16000):
        return self._segments


class _Seg:
    def __init__(self, dur: int):
        self.duration_ms = dur


@pytest.mark.asyncio
async def test_vad_guard_skips_stt_when_no_speech():
    stt = _StubSTT("should-not-run")
    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=stt,
        chat_func=lambda _u, _t: {"response": "ok"},
        vad_service=_StubVAD([]),
    )

    audio = base64.b64encode(b"RIFF" + b"\x00" * 40).decode("utf-8")
    ws = _FakeWS([{"type": "audio", "chunk": audio, "user_id": "u1"}])
    await handler.handle(ws)

    assert stt.calls == 0
    transcript_errs = [e for e in ws.sent if e.get("type") == "transcript" and e.get("error")]
    assert transcript_errs


@pytest.mark.asyncio
async def test_post_tts_holdoff_skips_new_audio():
    stt = _StubSTT("second")
    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=stt,
        chat_func=lambda _u, _t: {"response": "ok"},
        vad_service=_StubVAD([_Seg(300)]),
    )

    handler._last_audio_send_ms = __import__("time").monotonic() * 1000 - (POST_TTS_HOLDOFF_MS - 100)
    audio = base64.b64encode(b"RIFF" + b"\x00" * 40).decode("utf-8")
    ws = _FakeWS([{"type": "audio", "chunk": audio, "user_id": "u1"}])
    await handler.handle(ws)

    assert stt.calls == 0
    errs = [e for e in ws.sent if e.get("type") == "transcript" and e.get("error") == "Could not understand audio"]
    assert errs


@pytest.mark.asyncio
async def test_turn_lock_serializes_overlapping_turns():
    order: list[str] = []

    def chat_func(_user, text):
        import time
        order.append(f"start:{text}")
        time.sleep(0.05)
        order.append(f"end:{text}")
        return {"response": f"resp-{text}"}

    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=_StubSTT(),
        chat_func=chat_func,
        vad_service=_StubVAD([_Seg(300)]),
    )

    ws1 = _FakeWS([])
    ws2 = _FakeWS([])

    async def do_turn(ws, text):
        await handler._process_text_chat(ws, text, "u")

    await asyncio.gather(do_turn(ws1, "a"), do_turn(ws2, "b"))

    assert order in (["start:a", "end:a", "start:b", "end:b"], ["start:b", "end:b", "start:a", "end:a"])
    assert handler._turn_in_progress is False


def test_sentence_chunker_first_chunk_aggressive_split():
    chunker = SentenceChunker(soft_limit_chars=24)
    chunks = chunker.push("你好呀，我们今天来测试第一块分段，后面继续补充内容")
    assert chunks
    # First chunk should be short due to first-chunk soft limit + clause split.
    assert len(chunks[0]) <= 12


@pytest.mark.asyncio
async def test_ttfa_logging_emitted(capsys):
    def stream_chat(_u, _t):
        yield "你好，"
        yield "这是第二句。"

    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=_StubSTT(),
        chat_func=lambda _u, _t: {"response": "unused"},
        stream_chat_func=stream_chat,
        vad_service=_StubVAD([_Seg(300)]),
    )

    ws = _FakeWS([])
    await handler._process_text_chat(ws, "hello", "u1")
    out = capsys.readouterr().out
    assert "[WS] TTFA:" in out


def test_echo_detection_helper():
    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=_StubSTT(),
        chat_func=lambda _u, _t: {"response": "ok"},
        vad_service=_StubVAD([_Seg(300)]),
    )
    handler._last_response_text = "hello world this is ani speaking"
    assert handler._is_echo("hello world ani") is True
    assert handler._is_echo("different sentence entirely") is False


class _StubFiller:
    def __init__(self):
        self.calls = 0

    def get_filler(self, lang: str = "zh-CN"):
        self.calls += 1
        return b"RIFF" + b"\x00" * 32, [{"phoneme": "SIL", "start_ms": 0, "end_ms": 60}]


def test_filler_audio_service_init_and_get_filler(monkeypatch):
    calls = []

    def _fake_synthesize(self, text: str):
        calls.append(text)
        return (b"RIFF" + text.encode("utf-8"), [{"phoneme": "SIL", "start_ms": 0, "end_ms": 50}])

    monkeypatch.setattr("app.voice.tts_service.FallbackTTSService.synthesize", _fake_synthesize)

    svc = FillerAudioService()
    # Allow background pre-generation thread to run.
    import time as _time
    _time.sleep(0.05)

    audio, phonemes = svc.get_filler("zh-CN")
    assert audio.startswith(b"RIFF")
    assert phonemes
    assert calls


@pytest.mark.asyncio
async def test_filler_trigger_single_send_after_1200ms(capsys):
    filler = _StubFiller()

    def stream_chat(_u, _t):
        time.sleep(1.25)
        yield "等待一下"
        yield "，马上好。"
        yield "继续回答。"

    handler = AvatarWebSocketHandler(
        state_machine=ConversationStateMachine(),
        emotion_mapper=EmotionMapper(),
        tts_service=_StubTTS(),
        stt_service=_StubSTT(),
        chat_func=lambda _u, _t: {"response": "unused"},
        stream_chat_func=stream_chat,
        vad_service=_StubVAD([_Seg(300)]),
        filler_service=filler,
    )

    ws = _FakeWS([])
    await handler._process_text_chat(ws, "hello", "u1")

    out = capsys.readouterr().out
    assert filler.calls == 1
    assert "[WS] filler_after_ms=" in out
    assert "[WS] TTFA:" in out
